project:
  type: book

book:
  title: "STAT 8678 - SAS Programming & Data Analysis"
  author: "Chi-Kuang Yeh"
  date: today
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters: 
      - part1_1_intro_operation.qmd
      - part1_2_sas_syntax.qmd
      - part1_3_import_export.qmd
      - part1_4_rv.qmd
    - part: "Statistical Analysis"
      chapters:
      - part2_1_intro_inference1.qmd
      - part2_2_intro_inference2.qmd
      - part2_3_1sample_nonparametric_test.qmd
      - part2_4_1sample_proportion_test.qmd
      - part2_5_sas_marco.qmd
      - part2_6_chi-square.qmd
      - part2_7_power.qmd
      - part2_8_2sample_t.qmd
    - part: "Regression Analysis"
      chapters:
      - part3_1_ANOVA.qmd
    - references.qmd
  navbar:
    right:
      - icon: github
        href: https://github.com/chikuang/Teaching-Stat8678
        aria-label: GitHub
      - icon: file-pdf
        href: ./STAT-8678---SAS-Programming---Data-Analysis.pdf
        aria-label: Download PDF

bibliography: references.bib

execute:
  cache: true
  freeze: auto

format:
  html:
    theme:
      - flatly
      - brand
    css: custom-callouts.css
    filters:
      - addcalloutid.lua
    cache: true
  pdf:
    documentclass: scrreprt
    filters:
      - addcalloutid.lua
    cache: true

editor: visual