project:
  type: book

book:
  title: "Stat 8678 - SAS Programming & Data Analysis"
  author: "Chi-Kuang Yeh"
  date: today
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters: 
      - part1_intro.qmd
      - part1_sas_syntax.qmd
      - part1_import_export.qmd
      - part1_rv.qmd
    - part: "Statistical Analysis"
      chapters:
      - part2_intro_inference1.qmd
      - part2_intro_inference2.qmd
      - part2_1sample_nonparametric_test.qmd
      - part2_1sample_proportion_test.qmd
      - part2_sas_marco.qmd
      - part2_chi_square.qmd
    - references.qmd
  navbar:
    right:
      - icon: github
        href: https://github.com/chikuang/Teaching-Stat8678
        aria-label: GitHub
      - icon: file-pdf
        href: ./STAT-8678---Applied-Bayesian-Statistics.pdf
        aria-label: Download PDF

bibliography: references.bib

execute:
  cache: true
  freeze: auto

format:
  html:
    theme:
      - zephyr
      - brand
    css: custom-callouts.css
    filters:
      - addcalloutid.lua
    cache: true
  pdf:
    documentclass: scrreprt
    filters:
      - addcalloutid.lua
    cache: true

editor: visual