# Preface {.unnumbered}

## Description

This course covers programming using the SAS statistical software package, and it provides an introduction to data analysis stressing the implementation using SAS.

Topics include two main parts:

1)  **SAS Programming**: data management and manipulation, basic procedures, macro programming;
2)  **Data Analysis**: descriptive statistical analysis, one- and two-sample inference, basic categorical data analysis, regression analysis, and other selected topics.

### Prerequisites

MATH 4544/6544 -- Biostatistics, or equivalent.

### Instructor

[Chi-Kuang Yeh](https://chikuang.github.io/), Assistant Professor in the Department of Mathematics and Statistics, Georgia State University.

-   Office: Suite 1407, 25 Park Place.
-   Email: [cyeh\@gsu.edu](mailto:cyeh@gsu.edu).

## Office Hour

10:00--13:00 on Monday, or by appointment.

## Grade Distribution

-   Assignments: 60%
-   Exam: 20%
-   Project: 20%

## Assignment

-   [x] A1, due on Jan 28, 2026
-   [x] A2, due on Feb 8, 2026
-   [x] A3, due on Feb 15, 2026
-   [x] A4, due on Feb 28, 2026
-   [x] A5, due on Mar 18, 2026
-   [ ] A6, TBA

## Midterm

-   [x] March 4, 2026

## Final Project

-   [ ] Due on April 27, 2026

More information can be found on the [project page](https://chikuang.github.io/course/stat8678/project.html)

## Topics and Corresponding Lectures

Those chapters are based on the lecture notes. This part will be updated frequently.

| Status |                  Topic                   | Lecture |
|:------:|:----------------------------------------:|:-------:|
|   ✅   |           Welcome and Overview           |    1    |
|        |          **📘 Part 1: Basics**           |         |
|   ✅   |           Basic SAS Operation            |    2    |
|   ✅   |                SAS Syntax                |    3    |
|   ✅   |          Import and Export Data          |    4    |
|   ✅   |             Random Variable              |    5    |
|        |   **📘 Part 2: Statistical Analysis**    |         |
|   ✅   | Introduction to Statistical Inference I  |    6    |
|   ✅   | Introduction to Statistical Inference II |    7    |
|   ✅   |      One Sample Nonparametric Test       |    8    |
|   ✅    |        One Sample Proportion Test        |    9    |
|   ✅     |        Introduction to SAS Marco         |   10    |
|  ✅    |        Chi-Square GoF test|   11   |
|    ✅    |        Power Analysis and Calculation     (Recorded)  |   12  |
| ✅ ️  |        🛠  Class Activity I |   13  |
|    | **📜 Exam 🖌️ **  | 14 |
| ✅    |         Two Sample $t$-test for Independent and Paired Datasets   |   15  |
|        |   **📘 Part 3: Regression Analysis **    |         |
|   ✅   |         Analysis of Variance   | 16  |
|     |        ⛱ Spring Break  🌊    |   |
|   ✅   |        🛠 Class Activity II  |17  |
|   ✅   |         Intro to Regression Analysis     | 18 |
|   ⏳   |         Regression with Interaction Effects   | TBA|
|   ⏳   |         Linear Mixed Effects Model I   |  TBA |
|   ⏳   |         Linear Mixed Effects Model II   | TBA|
<!-- 🚧🛠️⏳   -->

## Recommended Textbooks

-   [Statistics 480: Introduction to SAS](https://online.stat.psu.edu/statprogram/stat480), The Pennsylvania State University.

-   [SAS Training](https://www.sas.com/en_us/training/overview.html), SAS Institute.

-   [SAS Resources](https://stats.oarc.ucla.edu/sas/), University of California, Los Angeles.

## Acknowledgments

Special thanks to [Li-Hsiang Lin](https://cas.gsu.edu/profile/li-hsiang-lin/) for providing the base materials given on this website.
