# Import and Export Dataset

Learning objective:

1.  Import a csv file into SAS
2.  Export a csv file from SAS after data process

One of the strengths of SAS as a data analysis tool is its ability to read data from many sources,
subset or combine data sets, and modify the datasets to accomplish various tasks. The most
common types of external data sets used in SAS are EXCEL files (XLS extent), comma separated
value files (CSV extent) and various space separate text files (PRN or TXT extent). A CSV file is
actually a text file and can be read in any text reader (NOTEPAD or WORDPAD in Windows).
In fact, the SAS files themselves, as well as the LOG and the LST files produced by a SAS by a
batch submit, are also simple text files

## Reading from External Files

The **PROC IMPORT** statement is the best way to enter external data sets. The CSV file we will
be using is called “grades.csv”. Download and save it in your favourite folder and mark the complete
path to it. Then use the following code to import it, making sure you put the correct path on the
**DATAFILE** argument.

``` r
PROC IMPORT OUT= GRADES_temp
DATAFILE= "Put Your Path Here/grades_temp.csv"
DBMS=CSV REPLACE;
GETNAMES=YES;
DATAROW=2;
RUN;
```

The **IMPORT** statement reads the dataset and stores it as the value designated by “OUT” in this case it will be saved as “Grades” in the library “Work”.

The **DBMS** statement defines the type of input SAS should be reading. The following table gives you all the possible choices. The REPLACE argument forces SAS to overwrite any older datasets with the same name.

The **GETNAMES** = YES or NO statement for spreadsheets and delimited external files, determines whether to generate SAS variable names from the column names in the input file’s first row of data. If you specify **GETNAMES** = NO or if the column names are not valid SAS names, PROC IMPORT uses the variable names VAR0, VAR1, VAR2, and so on. You may replace the equals sign with a blank.